### ISSUE TITLE
Reg. Usage of axis module

### ISSUE THREAD

**Issue by sayasree** [toddmotto/axis#10]
Hi Todd,

I had installed the 'axis' module (with $ npm install axis). When I tried to use it, I got the following error:

------- My Code --------
var axis = require('axis');
var s = 'todd';
console.log(s, ": is a ", axis.isString(s));
------------
console.log(s, ": is a ", axis.isString(s));
                               ^
TypeError: axis.isString is not a function
    at Object.<anonymous> (/home/sreeni/Saya/Programming/NodeJS/t.js:4:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
-----------
I am missing something?

Regards,
  --Sreeni Saya

**Comment by hAbd0u** [comment]
Try this:
` $ npm install -g axis`

**Comment by sayasree** [comment]
Hi,

Thanks for the reply.

Regards,
  --Sreeni Saya
